config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end

  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true

  def save_total_votes
    self.update_column(:total_votes, self.total_votes)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by slug: params[:post_id]
    @comment = @post.comments.build(params.require(:comment).permit(:body))

    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was successfully added"
      @comment.save_total_votes
      redirect_to post_path(@post)
    else
      @post.reload
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])
    if @vote.valid?
       @comment.save_total_votes
    end

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted"
        else
          flash[:error] = "You can only vote once"
        end
        redirect_to :back
      end
      format.js
    end
  end


end

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class='row'>
  <div class="span0 well text-center comment_votes">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post' , remote: true, style: 'display: block;' do %>
        <i class="icon-arrow-up"></i>
      <% end %>
    <% end %>
    <small id='comment_<%=comment.to_param%>_votes'><%= "#{comment.total_votes} votes" %></small>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post' , remote: true, style: 'display: block;' do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>

  <div class='span8 well'>
    <em>"<%= comment.body %>"</em>
    <% if show_post %>
    on <%= link_to comment.post.title, post_path(comment.post)%>
    <% end %>
    <p>
      <span class='quiet'>by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
      <small> at <%= format_timestamp(comment.created_at) %> </small>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.to_param %>_votes").html("<%= @comment.total_votes %> votes")
<% else %>
  $("#comment_<%= @comment.to_param %>_votes").parent().before(alert_error("You can only vote once"))
<% end %>
s