config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end

  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  sluggable_column :title

  def save_total_votes
    self.update_column(:total_votes, self.total_votes)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action  :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5, order: 'total_votes DESC')

    respond_to do |format|
      format.html
      format.xml { render xml: @posts }
      format.json { render json: @posts }
    end
  end

  def show
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.xml { render xml: @post }
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was successfully created"
      @post.save_total_votes
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      flash[:notice] = "Your post was successfully updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
     if @vote.valid?
        @post.save_total_votes
     end

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted"
        else
          flash[:error] = "You can only vote once"
        end
        redirect_to :back
      end
      format.js
    end

  end

private
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end
end

app/views/posts/_form.html.erb
<%= render 'shared/errors', errors: @post.errors %>

<div class='well' >
  <%= form_for @post do |f| %>
    <div class='control-group' >
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='control-group' >
      <%= f.label :utl %>
      <%= f.text_field :url %>
    </div>
    <div class='control-group' >
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <div class='control-group' >
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <%= cb.label(class: 'checkbox inline') {cb.check_box(class:'checkbox') + cb.text} %>
      <% end %>
    </div>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class='row'>
  <div class="span1 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true, style: 'display: block;' do %>
        <i class="icon-arrow-up"></i>
      <% end %>
    <% end %>
    <small id='post_<%=post.to_param%>_votes'> <%= pluralize(post.total_votes, 'vote') %></small>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true, style: 'display: block;'  do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>

  <div class='span8 well'>
    <%= render post.categories %>
    <h4> <%= link_to post.title, fix_url(post.url) %> </h4>
    <p> <%= post.description %> </p>
    <p>
      <span class='quiet'>Posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small> at <%= format_timestamp(post.created_at) %> </small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit the post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Post" %>

<%= will_paginate %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

<%= will_paginate %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a new post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<!-- if logged_in? && (current_user == @post.creator || current_user.admin?) -->
<% if logged_in? %>
  <p class='pull-right'>
    [<%= link_to 'Edit this post', edit_post_path(@post) %>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<p class='lead'>
  <%= link_to @post.title, fix_url(@post.url) %>
  <hr/>
</p>

<p>
  <%= @post.description %>
  <hr/>
</p>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <% render 'shared/errors', errors: @comment.errors %>
    <div class='control-group' >
      <%= f.label :body, 'Leave a comment' %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
    </div>
    <%= f.submit('Create Commment', class: 'btn btn-primary') %>
  <% end %>
<% end %>

<h4> Comments: </h4>
<% comments = @post.comments.paginate(page: params[:page], per_page: 5, order: 'total_votes DESC') %>
<%= will_paginate comments %>
<%= render comments %>
<%= will_paginate comments %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.to_param %>_votes").html("<%= pluralize(@post.total_votes, 'vote') %>")
<% else %>
  $("#post_<%= @post.to_param %>_votes").parent().before(alert_error("You can only vote once"))
<% end %>